/**
 * Nguồn dữ liệu trang /services — đồng bộ với:
 * - 03-departments/04-san-pham/service-catalog-v1.md
 * - 03-departments/04-san-pham/fdi-lifecycle-full-map.md
 */

export type ServiceMode = "self" | "partner" | "hybrid";

export type LifecyclePhase = {
  id: string;
  short: string;
  name: string;
  nameZh: string;
  duration: string;
  mindset: string;
  color: string;
  border: string;
  docSlug: string[];
};

export type ServiceItem = {
  id: string;
  name: string;
  nameZh?: string;
  phases: string[];
  tier: "entry" | "policy" | "logistics" | "hub" | "exit";
  tierLabel: string;
  when: string;
  deliverable: string;
  priceUsd: string;
  duration: string;
  mode: ServiceMode;
  modeLabel: string;
  docSlug?: string[];
  featured?: boolean;
};

export const LIFECYCLE_PHASES: LifecyclePhase[] = [
  {
    id: "G0",
    short: "G0",
    name: "Quyết định rời Trung Quốc",
    nameZh: "决定离开中国",
    duration: "1–6 tháng",
    mindset: "Có nên đi? China+1 đi đâu?",
    color: "bg-stone-100 text-stone-800",
    border: "border-stone-300",
    docSlug: ["03-departments", "04-san-pham", "fdi-lifecycle-full-map"],
  },
  {
    id: "G1",
    short: "G1",
    name: "Tiếp cận & tìm hiểu VN",
    nameZh: "了解越南",
    duration: "2–8 tuần",
    mindset: "VN có phù hợp ngành tôi không?",
    color: "bg-slate-100 text-slate-800",
    border: "border-slate-300",
    docSlug: ["03-departments", "04-san-pham", "fdi-lifecycle-full-map"],
  },
  {
    id: "G2",
    short: "G2",
    name: "Khảo sát & chọn địa điểm",
    nameZh: "选址考察",
    duration: "1–3 tháng",
    mindset: "Thái Nguyên hay Hải Phòng? Giá đất?",
    color: "bg-emerald-100 text-emerald-900",
    border: "border-emerald-400",
    docSlug: ["03-departments", "04-san-pham", "package-a1-deliverable"],
  },
  {
    id: "G3",
    short: "G3",
    name: "Cam kết & thành lập pháp nhân",
    nameZh: "投资承诺与公司设立",
    duration: "2–4 tháng",
    mindset: "IRC, công ty, con dấu?",
    color: "bg-teal-100 text-teal-900",
    border: "border-teal-400",
    docSlug: ["03-departments", "02-phap-ly", "ctcp-ho-so-checklist"],
  },
  {
    id: "G4",
    short: "G4",
    name: "Thiết lập nhà máy",
    nameZh: "建厂准备",
    duration: "6–18 tháng",
    mindset: "Đất, xây, máy, tuyển người?",
    color: "bg-cyan-100 text-cyan-900",
    border: "border-cyan-400",
    docSlug: ["07-operations", "sop-b1-on-site"],
  },
  {
    id: "G5",
    short: "G5",
    name: "Vận hành sản xuất",
    nameZh: "生产经营",
    duration: "3–15+ năm",
    mindset: "Nhập NVL, SX, xuất khẩu, thuế?",
    color: "bg-amber-100 text-amber-900",
    border: "border-amber-400",
    docSlug: ["03-departments", "04-san-pham", "factory-operations-playbook-vn"],
  },
  {
    id: "G6",
    short: "G6",
    name: "Mở rộng quy mô",
    nameZh: "扩大规模",
    duration: "Ongoing",
    mindset: "Thêm line, thêm vốn, tỉnh thứ 2?",
    color: "bg-violet-100 text-violet-900",
    border: "border-violet-400",
    docSlug: ["03-departments", "04-san-pham", "product-bundles"],
  },
  {
    id: "G7",
    short: "G7",
    name: "Di dời sang tỉnh khác",
    nameZh: "省内迁移",
    duration: "6–24 tháng",
    mindset: "Chuyển NM sang tỉnh khác trong VN?",
    color: "bg-orange-100 text-orange-900",
    border: "border-orange-400",
    docSlug: ["04-research", "2026-07", "legal-g7-g8-relocation-exit"],
  },
  {
    id: "G8",
    short: "G8",
    name: "Thoái vốn / về Trung Quốc",
    nameZh: "撤资回国",
    duration: "12–36 tháng",
    mindset: "Đóng NM, máy về TQ, giải thể?",
    color: "bg-rose-100 text-rose-900",
    border: "border-rose-400",
    docSlug: ["04-research", "2026-07", "legal-g7-g8-relocation-exit"],
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: "A0",
    name: "Tư vấn sơ bộ",
    nameZh: "免费咨询",
    phases: ["G0", "G1"],
    tier: "entry",
    tierLabel: "Tiếp cận",
    when: "Lead mới, chưa chắc vào Việt Nam",
    deliverable: "Call 30 phút + checklist PDF 10 mục",
    priceUsd: "Miễn phí",
    duration: "1 tuần",
    mode: "self",
    modeLabel: "LONGTV",
    featured: true,
  },
  {
    id: "A1",
    name: "Báo cáo desk research",
    nameZh: "投资考察报告",
    phases: ["G1", "G2", "G6", "G7"],
    tier: "policy",
    tierLabel: "Chính sách & địa điểm",
    when: "Chưa chọn tỉnh hoặc cần so sánh TN / HP",
    deliverable: "PDF 15–20 trang + slide 10 + pitch 60 phút",
    priceUsd: "2.500 – 4.000",
    duration: "2–3 tuần",
    mode: "self",
    modeLabel: "LONGTV",
    docSlug: ["03-departments", "04-san-pham", "package-a1-deliverable"],
    featured: true,
  },
  {
    id: "H1",
    name: "Brief chính sách & bản tin",
    phases: ["G0", "G1", "G5", "G6"],
    tier: "hub",
    tierLabel: "Hub kết nối",
    when: "Cần cập nhật NĐ tỉnh, xu hướng FDI",
    deliverable: "Bản tin tháng, brief chính sách",
    priceUsd: "Trong retainer / miễn phí lead",
    duration: "Hàng tháng",
    mode: "self",
    modeLabel: "LONGTV",
  },
  {
    id: "A2",
    name: "Làm việc Sở & xin ưu đãi",
    nameZh: "政策申请与政府对接",
    phases: ["G2", "G3"],
    tier: "policy",
    tierLabel: "Chính sách & địa điểm",
    when: "Đã chọn tỉnh, cần ưu đãi & timeline IRC",
    deliverable: "Biên bản Sở/KCN + checklist hồ sơ",
    priceUsd: "4.000 – 6.000",
    duration: "1–3 tháng",
    mode: "hybrid",
    modeLabel: "LONGTV + luật",
    docSlug: ["04-research", "2026-07", "provincial-incentives"],
  },
  {
    id: "B1",
    name: "On-site + hải quan starter",
    nameZh: "实地考察与海关入门",
    phases: ["G2", "G4", "G5", "G7", "G8"],
    tier: "logistics",
    tierLabel: "Logistics & hải quan",
    when: "Cần gặp Sở/KCN hoặc setup hải quan XNK",
    deliverable: "2 ngày on-site + báo cáo bổ sung + SOP XNK",
    priceUsd: "8.000 – 12.000 + CPEX",
    duration: "4–6 tuần",
    mode: "self",
    modeLabel: "LONGTV",
    docSlug: ["07-operations", "sop-b1-on-site"],
    featured: true,
  },
  {
    id: "DD-01",
    name: "Due diligence đất / đối tác",
    phases: ["G2"],
    tier: "policy",
    tierLabel: "Chính sách & địa điểm",
    when: "Trước ký thuê đất hoặc MOU",
    deliverable: "Báo cáo pháp lý quyền sử dụng đất",
    priceUsd: "3.000 – 8.000",
    duration: "2–4 tuần",
    mode: "partner",
    modeLabel: "Luật sư đối tác",
  },
  {
    id: "B2",
    name: "Thành lập pháp nhân & IRC",
    nameZh: "公司设立与投资执照",
    phases: ["G3", "G4", "G6", "G7"],
    tier: "policy",
    tierLabel: "Chính sách & địa điểm",
    when: "Cam kết đầu tư, cần CTCP/DN tại VN",
    deliverable: "IRC, ERC, MST, con dấu — NM hoạt động",
    priceUsd: "6.000 – 10.000",
    duration: "6–12 tuần",
    mode: "hybrid",
    modeLabel: "Luật + PM LONGTV",
    docSlug: ["03-departments", "02-phap-ly", "ctcp-ho-so-checklist"],
    featured: true,
  },
  {
    id: "A3-PM",
    name: "PM thiết lập nhà máy",
    nameZh: "建厂项目管理",
    phases: ["G4"],
    tier: "policy",
    tierLabel: "Chính sách & địa điểm",
    when: "Cần một đầu mối điều phối setup",
    deliverable: "Timeline master + checklist 50 mục G4",
    priceUsd: "15.000 – 30.000",
    duration: "6 tháng",
    mode: "hybrid",
    modeLabel: "PM LONGTV",
  },
  {
    id: "ENV-01",
    name: "Môi trường & PCCC",
    phases: ["G4"],
    tier: "policy",
    tierLabel: "Chính sách & địa điểm",
    when: "Ngành cần ĐTM, giấy phép môi trường",
    deliverable: "ĐTM, GP môi trường (tùy ngành)",
    priceUsd: "5.000 – 20.000",
    duration: "2–6 tháng",
    mode: "partner",
    modeLabel: "Tư vấn môi trường",
  },
  {
    id: "HR-01",
    name: "Tuyển dụng khởi điểm",
    phases: ["G4"],
    tier: "hub",
    tierLabel: "Hub kết nối",
    when: "NM cần 20–100 lao động đầu tiên",
    deliverable: "Tuyển dụng + mẫu HĐLĐ",
    priceUsd: "Theo head / project",
    duration: "1–2 tháng",
    mode: "partner",
    modeLabel: "HR agency",
  },
  {
    id: "B1-ext",
    name: "Nhập thiết bị / dây chuyền TQ",
    phases: ["G4"],
    tier: "logistics",
    tierLabel: "Logistics & hải quan",
    when: "Máy móc từ Trung Quốc vào VN",
    deliverable: "HS code + tờ khai nhập + tạm nhập",
    priceUsd: "2.000 – 5.000 / lô",
    duration: "Theo lô",
    mode: "self",
    modeLabel: "LONGTV + Oz",
  },
  {
    id: "B3",
    name: "Retainer chuỗi nhập–SX–xuất",
    nameZh: "进出口生产顾问",
    phases: ["G5"],
    tier: "logistics",
    tierLabel: "Logistics & hải quan",
    when: "NM đang chạy, ≥10 tờ khai/tháng",
    deliverable: "PM XNK + đối soát BOM + báo cáo tháng",
    priceUsd: "2.000 – 5.000 / tháng",
    duration: "6–12 tháng",
    mode: "hybrid",
    modeLabel: "LONGTV + forwarder",
    docSlug: ["03-departments", "04-san-pham", "factory-operations-playbook-vn"],
    featured: true,
  },
  {
    id: "B2-log",
    name: "Logistics pack",
    nameZh: "物流方案",
    phases: ["G5"],
    tier: "logistics",
    tierLabel: "Logistics & hải quan",
    when: "Hàng TQ → cảng HP → KCN",
    deliverable: "Báo giá 2–3 tuyến + SOP giao nhận",
    priceUsd: "1.500 – 3.000 + shipment",
    duration: "Theo tuyến",
    mode: "hybrid",
    modeLabel: "Điều phối + forwarder",
  },
  {
    id: "H3",
    name: "Kế toán & thuế NM",
    nameZh: "会计税务",
    phases: ["G4", "G5", "G8"],
    tier: "hub",
    tierLabel: "Hub kết nối",
    when: "Vận hành & quyết toán CIT/VAT",
    deliverable: "Sổ sách, BCTC, quyết toán thuế",
    priceUsd: "800 – 2.500 / tháng",
    duration: "Ongoing",
    mode: "partner",
    modeLabel: "CPA + PM",
  },
  {
    id: "HR-02",
    name: "Payroll & BHXH",
    phases: ["G5"],
    tier: "hub",
    tierLabel: "Hub kết nối",
    when: "Trả lương, BHXH hàng tháng",
    deliverable: "Tính lương + báo cáo lao động",
    priceUsd: "500 – 1.500 / tháng",
    duration: "Ongoing",
    mode: "partner",
    modeLabel: "HR đối tác",
  },
  {
    id: "H2",
    name: "Tư vấn pháp lý & review HĐ",
    phases: ["G2", "G3", "G5", "G7", "G8"],
    tier: "hub",
    tierLabel: "Hub kết nối",
    when: "Review hợp đồng thuê đất, NDA, MOU",
    deliverable: "Memo pháp lý, review HĐ",
    priceUsd: "Theo scope",
    duration: "Ad-hoc",
    mode: "hybrid",
    modeLabel: "LONGTV + luật",
    docSlug: ["03-departments", "02-phap-ly", "templates", "00-index"],
  },
  {
    id: "H4",
    name: "Kết nối KCN, Sở, MOU",
    phases: ["G2", "G6", "G7"],
    tier: "hub",
    tierLabel: "Hub kết nối",
    when: "Cần đầu mối chính quyền / KCN",
    deliverable: "Giới thiệu, MOU, pipeline",
    priceUsd: "Trong gói / referral",
    duration: "Ongoing",
    mode: "self",
    modeLabel: "LONGTV",
  },
  {
    id: "C1",
    name: "Cố vấn tháng",
    phases: ["G5", "G6"],
    tier: "hub",
    tierLabel: "Hub kết nối",
    when: "Cần 4h tư vấn chiến lược/tháng",
    deliverable: "4h call + email support",
    priceUsd: "1.500 / tháng",
    duration: "Ongoing",
    mode: "self",
    modeLabel: "LONGTV",
  },
  {
    id: "G7-01",
    name: "Đánh giá rủi ro chuyển tỉnh",
    nameZh: "迁址风险评估",
    phases: ["G7"],
    tier: "exit",
    tierLabel: "Di dời & thoái",
    when: "NM muốn chuyển sang tỉnh khác trong VN",
    deliverable: "Memo phạt đất, mất ưu đãi, timeline",
    priceUsd: "3.000 – 5.000",
    duration: "2–3 tuần",
    mode: "self",
    modeLabel: "LONGTV",
    docSlug: ["04-research", "2026-07", "legal-g7-g8-relocation-exit"],
  },
  {
    id: "G7-Pack",
    name: "Gói di dời tỉnh (full)",
    nameZh: "省内迁移全套",
    phases: ["G7"],
    tier: "exit",
    tierLabel: "Di dời & thoái",
    when: "Thực hiện chuyển NM sang tỉnh mới",
    deliverable: "G7-01 + A1 tỉnh mới + PM + B2 điều chỉnh IRC",
    priceUsd: "12.000 – 25.000",
    duration: "6–18 tháng",
    mode: "hybrid",
    modeLabel: "PM LONGTV",
    featured: true,
  },
  {
    id: "G8-01",
    name: "Kế hoạch thoái vốn",
    nameZh: "撤资规划",
    phases: ["G8"],
    tier: "exit",
    tierLabel: "Di dời & thoái",
    when: "Quyết định đóng NM / về Trung Quốc",
    deliverable: "Lộ trình 12–36 tháng: thuế, LĐ, đất, máy",
    priceUsd: "5.000 – 8.000",
    duration: "2–4 tuần",
    mode: "hybrid",
    modeLabel: "PL + H3",
  },
  {
    id: "G8-Pack",
    name: "Gói giải thể & về TQ (full)",
    nameZh: "清算回国全套",
    phases: ["G8"],
    tier: "exit",
    tierLabel: "Di dời & thoái",
    when: "Thực hiện giải thể, xuất máy về TQ",
    deliverable: "G8-01 + quyết toán thuế + giải thể + xuất máy",
    priceUsd: "15.000 – 40.000+",
    duration: "12–36 tháng",
    mode: "hybrid",
    modeLabel: "Luật + LONGTV",
    docSlug: ["04-research", "2026-07", "legal-g7-g8-relocation-exit"],
    featured: true,
  },
];

export const TYPICAL_JOURNEY = [
  { phase: "G0–G1", services: ["A0", "A1", "H1"] },
  { phase: "G2", services: ["A1", "A2", "B1", "DD-01"] },
  { phase: "G3–G4", services: ["B2", "A3-PM", "B1-ext", "H3"] },
  { phase: "G5", services: ["B3", "B2-log", "H3", "HR-02", "C1"] },
  { phase: "G6", services: ["A1", "B2", "A3-PM"] },
  { phase: "G7", services: ["G7-Pack"] },
  { phase: "G8", services: ["G8-Pack"] },
];

export const COMPANY_POSITIONING = {
  tagline: "Đồng hành nhà máy FDI Trung Quốc — từ lúc sang Việt Nam đến khi mở rộng, di dời hoặc về nước",
  provinces: "Thái Nguyên & Hải Phòng",
  logistics: "Logistics & hải quan miền Bắc",
  hub: "Pháp lý · Kế toán · Kết nối KCN/Sở",
};

export function getServicesByPhase(phaseId: string): ServiceItem[] {
  return SERVICES.filter((s) => s.phases.includes(phaseId));
}

export function getServiceById(id: string): ServiceItem | undefined {
  return SERVICES.find((s) => s.id === id);
}

export const TIER_STYLES: Record<ServiceItem["tier"], { label: string; className: string }> = {
  entry: { label: "Tiếp cận", className: "bg-slate-100 text-slate-700" },
  policy: { label: "Chính sách & địa điểm", className: "bg-emerald-100 text-emerald-800" },
  logistics: { label: "Logistics & hải quan", className: "bg-amber-100 text-amber-900" },
  hub: { label: "Hub", className: "bg-indigo-100 text-indigo-800" },
  exit: { label: "Di dời & thoái", className: "bg-rose-100 text-rose-800" },
};
